name: Nanoku
favicon: null
layout_spectrum: 0.5425557235721499
typography_spectrum: 0.9617575278971344
title: nanoku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13986861798912287
  lightness: 0.9676024138461798
  saturation: 0.8171244547702372
  rhythmicContrast: 0.5659063686616719
purpose: []
