name: Nanoku
favicon: null
layout_spectrum: 0.97674
typography_spectrum: 0.13204
title: nanoku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e47b4c'
    - '#ffffff'
    - '#b6c3b9'
    - '#0d1919'
    - '#566a6a'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
